FROM lsiobase/ubuntu:xenial

# environment settings
ARG DEBIAN_FRONTEND="noninteractive"

# install packages
RUN \
 apt-get update && \
 apt-get install -y \
	apt-transport-https \
	lsb-release && \

 echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ xenial main" > \
	/etc/apt/sources.list.d/dotnetdev.list && \
 apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893 && \
 curl -sL https://deb.nodesource.com/setup_7.x | bash - && \
 apt-get update && \
 apt-get install -y \
	--no-install-recommends \
	build-essential \
	bzr \
	dirmngr \
	git \
	gnupg2 \
	libc6 \
	libcurl3 \
	libgcc1 \
	libgssapi-krb5-2 \
	libicu55 \
	liblttng-ust0 \
	libssl1.0.0 \
	libstdc++6 \
	libunwind8 \
	libuuid1 \
	mercurial \
	nodejs \
	openssh-client \
	p7zip-full \
	procps \
	subversion \
	wget \
	zlib1g && \

 apt-get install -y \
	dotnet-dev-1.0.4 && \

 npm install -g gulp && \

# cleanup
 rm -rf \
	/tmp/* \
	/var/lib/apt/lists/* \
	/var/tmp/*

# build ombi
RUN \
 git clone --branch=DotNetCore https://github.com/tidusjar/Ombi.git /projects/ombi && \
 cd /projects/ombi/src/Ombi && \
 dotnet restore && \
 npm install && \
 gulp publish && \
 dotnet build && \
 dotnet publish -c Release && \
 dotnet publish "../Ombi.Updater" -c Release && \
 cp /projects/ombi/src/Ombi/bin/Release/netcoreapp1.1/Swagger.xml /projects/ombi/src/Ombi/bin/Release/netcoreapp1.1/publish/Swagger.xml && \
 cp /projects/ombi/src/Ombi.Updater/bin/Release/netcoreapp1.1/publish/Ombi.Updater.dll /projects/ombi/src/Ombi/bin/Release/netcoreapp1.1/publish/Ombi.Updater.dll && \
 7z a Ombi_ubuntu.zip /projects/ombi/src/Ombi/bin/Release/netcoreapp1.1/publish

RUN \
 mkdir -p \
	/package && \
 cp /projects/ombi/src/Ombi/Ombi_ubuntu.zip /package/ && \
 chmod -R 777 /package

# Copy zip file out to mounted directory
CMD ["cp", "-avr", "/package", "/mnt/"]
