#!/usr/bin/with-contenv bash
# shellcheck shell=bash

mkdir -p /run/ombi-temp

# permissions
lsiown -R abc:abc \
    /run/ombi-temp \
    /config

if [[ -z ${LSIO_READ_ONLY_FS} ]]; then
    lsiown abc:abc /app/ombi/ClientApp/dist/browser/index.html
fi
