#!/usr/bin/with-contenv bash
# shellcheck shell=bash

mkdir -p /run/ombi-temp

# permissions
lsiown -R abc:abc \
    /run/ombi-temp \
    /config

lsiown abc:abc /app/ombi/ClientApp/dist/index.html > /dev/null 2>&1
