#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*          This image has been deprecated            *
*                                                    *
*           Use the multi-arch images at             *
*                                                    *
*                linuxserver/ombi                    *
*                                                    *
*      https://hub.docker.com/r/linuxserver/ombi     *
*                                                    *
*     https://github.com/linuxserver/docker-ombi     *
*                                                    *
*                                                    *
*                                                    *
******************************************************
******************************************************'
